// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetTrackedAnimeAll():Promise<Array<main.TrackedAnimeTableRow>>;

export function InsertTrackedAnime(arg1:number):Promise<void>;
